MetroEvents7/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace="account")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.LoginPage.as_view(), name="login"),
    path('register/', views.RegisterPage.as_view(), name="register"),
    path('logout/', views.logoutUser, name="logout"),

    path('myaccount/', views.HomePage.as_view(), name="myaccount"),

    path('administrator/', views.AdminPage.as_view(), name="administrator"),

    path('addEvent/', views.AddEvent.as_view(), name="addEvent"),

    path('organizer/', views.OrganizerPage.as_view(), name="organizer"),
    # path('organizer/addEvent/', views.organizerPage, name="organizer"),
]

account/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.admin import UserAdmin

# Create your models here.


class Comment(models.Model):
    comment = models.CharField(max_length=45, blank=True, null=True)


class Event(models.Model):
    event_type = models.CharField(max_length=200)

    participants = models.ManyToManyField(User, blank=True)
    start_date = models.DateField(
        default=timezone.now(), blank=True, null=True)
    end_date = models.DateField(default=timezone.now(), blank=True, null=True)

    upvotes = models.IntegerField(default=0, blank=True, null=True)
    comment = models.ManyToManyField(Comment, blank=True)

    def __str__(self):
        return self.event_type


class Request(models.Model):
    REQUEST_TYPE = (
        ('Join Event', 'Join Event'),
        ('Organizer Request', 'Organizer Request'),
    )
    REQUEST_STATUS = (
        ('Reviewing', 'Reviewing'),
        ('Accept', 'Accept'),
        ('Decline', 'Decline'),
    )

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True, related_name="+")
    requestType = models.CharField(
        max_length=30, null=True, choices=REQUEST_TYPE, default="Join Event")
    event = models.ForeignKey(
        Event, on_delete=models.SET_NULL, null=True, blank=True, related_name="+")

    status = models.CharField(max_length=30, null=True,
                              choices=REQUEST_STATUS, default="Reviewing")
    date_requested = models.DateTimeField(auto_now_add=True, blank=True)
    date_replied = models.DateTimeField(blank=True, null=True)
    replied_by = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True, related_name="+")

    def __str__(self):
        return self.requestType + " - " + str(self.id)


class Organizer(models.Model):
    organizer = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True, default=0)
    event = models.ManyToManyField(Event, blank=True)
    promotion_date = models.DateField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.organizer_id.username


# class Administrator(models.Model):
#     admin = models.OneToOneField(
#         User, on_delete=models.CASCADE, primary_key=True, default=0)
#     event = models.ManyToManyField(Event, blank=True)

#     def __str__(self):
#         return self.admin_id.username

account/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

account/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View

from django.contrib.auth import authenticate, login, logout

from django.contrib import messages
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group

from django.contrib.auth.decorators import login_required
# from django.utils.decorators import method_decorator

from .forms import CreateUserForm
from .models import User, Comment, Event, Organizer, Request


def format_date(objects):
    for object in objects:
        object.start_date = object.start_date.strftime("%Y-%m-%d")
        object.end_date = object.end_date.strftime("%Y-%m-%d")

#! REGISTER PAGE


class RegisterPage(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('account:myaccount')
        form = CreateUserForm()

        context = {'form': form}
        return render(request, 'register.html', context)

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')

            messages.success(
                request, 'Account was created for ' + username)

            return redirect('account:login')

        context = {'form': form}
        return render(request, 'register.html', context)


#! LOGIN PAGE
class LoginPage(View):
    def get(self, request):
        if request.user.is_authenticated:
            if not request.user.is_staff:
                return redirect('account:myaccount')
            elif request.user.is_superuser:
                return redirect('account:administrator')
            elif request.user.is_staff:
                return redirect('account:organizer')
            else:
                return redirect('account:myaccount')
        else:
            return render(request, "login.html")

    def post(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(
                request, username=username, password=password)

            if user is not None:
                login(request, user)
                if not user.is_staff:
                    return redirect('account:myaccount')
                elif user.is_superuser:
                    return redirect('account:administrator')
                elif user.is_staff:
                    return redirect('account:organizer')
                else:
                    return HttpResponse("ERROR")
            else:
                messages.info(request, 'Username OR password is incorrect')

            return render(request, 'login.html')


def logoutUser(request):
    logout(request)
    return redirect('account:login')

#! USER PAGE
# @method_decorator(login_required, name='dispatch')


class HomePage(View):
    def get(self, request):
        if request.user.is_authenticated:
            currentUser = request.user
            if currentUser.is_superuser:
                return redirect('account:administrator')
            elif currentUser.is_staff:
                return redirect('account:organizer')
            elif not request.user.is_staff:
                myEvents = Event.objects.filter(participants=currentUser)
                events = Event.objects.exclude(participants=currentUser)
                context = {
                    'myEvents': myEvents,
                    'events': events,
                }
                return render(request, 'useraccount.html', context)
            else:
                return HttpResponse("Error")

    def post(self, request):
        if 'request_joinbtn' in request.POST:
            currentUser = request.user
            eventid = request.POST.get('event_id')
            print(eventid)
            req = Request.objects.filter(status="Accept",
                                         user=currentUser, requestType="Join Event", event_id=eventid)
            if req:
                messages.info(
                    request, "You have already requested to join the event.")
                return redirect('account:myaccount')
            reqJoin = Request.objects.create(
                user=currentUser, requestType="Join Event", event_id=eventid)

            messages.info(
                request, "Your request to join the event will be up for reviewing")

        elif 'request_orgbtn' in request.POST:
            print(request.user.id)
            req = Request.objects.filter(
                user=request.user, requestType="Organizer Request")
            if req:
                messages.info(
                    request, "You have already requested to become an organizer.")
                return redirect('account:myaccount')
            reqOrg = Request.objects.create(
                user=request.user, requestType="Organizer Request")

            messages.info(
                request, "Your request to become an organizer is up for a review")
        elif 'submitUpvote' in request.POST:
            myeventid = request.POST.get('myevent-id')
            event = Event.objects.get(id=myeventid)

            btnradio = request.POST.get('btnradio')

            if btnradio == "upvote":
                event.upvotes = event.upvotes + 1
                event.save()
            elif btnradio == "downvote":
                event.upvotes = event.upvotes - 1
                event.save()
            messages.info(request, 'Upvote submitted successfully!')
        elif 'submitComment' in request.POST:
            myeventid = request.POST.get('myevent-id')
            event = Event.objects.get(id=myeventid)

            comments = request.POST.get('comment')
            print(comments)

            comment = Comment.objects.update(comment=comments)
            event.comment.add(comment)
            event.save()
            messages.info(request, 'Comment submitted successfully!')
        return redirect('account:myaccount')


#! Admin Page
# @method_decorator(login_required, name='dispatch')
class AdminPage(View):
    def get(self, request):
        if request.user.is_authenticated:
            currentUser = request.user
            if currentUser.is_superuser:
                requests = Request.objects.filter(
                    requestType="Organizer Request", status="Reviewing")
                events = Event.objects.all()
                users = User.objects.all()
                organizers = Organizer.objects.all()

                context = {
                    'users': users,
                    'events': events,
                    'organizers': organizers,
                    'requests': requests,
                }
                return render(request, 'adminAccount.html', context)
            elif not currentUser.is_staff:
                return redirect('account:myaccount')
            elif currentUser.is_staff:
                return redirect('account:organizer')
            else:
                return redirect('account:login')

        return redirect('account:login')

    def post(self, request):
        if 'grantAdminbtn' in request.POST:
            user = User.objects.get(id=request.POST.get("user-id"))

            user.is_staff = True
            user.is_superuser = True

            user.save()
        if 'requestorg_acceptbtn' in request.POST:
            userid = request.POST.get("user-id")
            requestid = request.POST.get("request-id")
            print(userid)
            print(requestid)
            req = Request.objects.get(id=requestid)
            organizer = Organizer.objects.create(organizer_id=userid)
            req.status = "Accept"
            req.date_replied = datetime.now()
            req.replied_by = request.user
            user = req.user
            user.is_staff = True
            organizer.save()
            req.save()
            user.save()
        elif 'requestorg_declinebtn' in request.POST:
            print("Request to be an organizer, DECLINED")
            req = Request.objects.get(id=request.POST.get("request-id"))
            req.status = "Decline"
            req.date_replied = datetime.now()
            req.replied_by = request.user
            req.save()

        if 'EditBtn' in request.POST:
            id = request.POST.get("event_id")
            event_type = request.POST.get("event_type")
            start_date = request.POST.get("start_date")
            end_date = request.POST.get("end_date")

            print(start_date)
            print(end_date)
            Event.objects.filter(id=id).update(
                event_type=event_type, start_date=start_date, end_date=end_date)
        elif 'DeleteBtn' in request.POST:
            print('Deleted Event')
            id = request.POST.get("event_id")
            Event.objects.filter(id=id).delete()
        return redirect('account:administrator')

#! ORGANIZER PAGE


# @method_decorator(login_required, name='dispatch')
class OrganizerPage(View):
    def get(self, request):
        if request.user.is_authenticated:
            currentUser = request.user
            if currentUser.is_superuser:
                return redirect('account:administrator')
            elif currentUser.is_staff:
                organizer = Organizer.objects.get(organizer_id=currentUser)
                myEvents = Event.objects.filter(organizer=organizer)

                requests = Request.objects.filter(
                    event_id__in=myEvents, status="Reviewing")

                context = {
                    'myEvents': myEvents,
                    'requests': requests,
                }
                return render(request, 'organizerAccount.html', context)
            elif not request.user.is_staff:

account/templates/addEvent.html
{% load static %}
<!DOCTYPE html>
<html lang="eng">

<head>
  <title>Add Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">


</head>

<style>
  .hello-msg {
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }

  .container {
    padding: 2rem 0rem;
  }

  h4 {
    margin: 2rem 0rem 1rem;
  }

  body {
    font-family: Arial, Helvetica, sans-serif;
  }

  * {
    box-sizing: border-box
  }

  /* Full-width input fields */
  input[type=text],
  input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 22px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
  }

  input[type=text]:focus,
  input[type=password]:focus {
    background-color: #ddd;
    outline: none;
  }

  hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
  }

  /* Set a style for all buttons */
  button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
  }

  button:hover {
    opacity: 1;
  }

  /* Extra styles for the cancel button */
  .cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
  }

  .createbtn {
    padding: 14px 20px;
    background-color: #3CB371;
  }

  /* Float cancel and signup buttons and add an equal width */
  .cancelbtn,
  .createbtn,
  .signupbtn {
    float: left;
    width: 50%;
  }

  /* Add padding to container elements */
  .container {
    padding: 16px;
  }

  /* Clear floats */
  .clearfix::after {
    content: "";
    clear: both;
    display: table;
  }

  /* Change styles for cancel button and signup button on extra small screens */
  @media screen and (max-width: 300px) {

    .cancelbtn,
    .createbtn,
    .signupbtn {
      width: 100%;
    }
  }
</style>

<body>
  {% block content %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account:addEvent' %}"><b>MetroEvents</b></a>
        </li>
      </ul>
    </div>

    <span class="hello-msg">Hello, {{request.user}}</span>
    <span><a class="hello-msg" href="{% url 'account:logout' %}" style="color: white;">Logout</a></span>

  </nav>

  <form id="event-form" method="POST" autocomplete="off" enctype="multipart/form-data" style="border:1px solid #ccc">
    {% csrf_token %}
    <div class="container">
      <h1>Event Form</h1>
      <p>Please fill in this form to create or organize an event.</p>
      <hr>

      <label for="type"><b>Event Type</b></label>
      <input id="eventType" type="text" placeholder="Enter Event Type" name="event_type" required>

      <label for="decription"><b>Start Date</b></label>
      <input id="date_started" type="date" name="start_date" required>

      <label for="decription"><b>End Date</b></label>
      <input id="eventenddate" type="date" name="end_date" required>
      <!-- <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p> -->
      <div class="container">
        <div class="clearfix">

          <a style="color: white; text-align: center;" type="button" class="cancelbtn"
            href="{% url 'account:login' %}">Cancel</a>

          <button style="color: white; text-align: center;" type="submit" class="createbtn">Create</button>
        </div>
      </div>
    </div>
  </form>
  {% endblock content %}
</body>

</html>

account/templates/organizerAccount.html
{% load static %}
<!DOCTYPE html>
<html lang="eng">

<head>
  <title>MetroEvents | Organizer</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
  <link rel="stylesheet" type="text/css" href="{% static '/css/main.css' %}">

</head>

<style>
  .hello-msg {
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }

  .container {
    padding: 2rem 0rem;
  }

  h4 {
    margin: 2rem 0rem 1rem;
  }

  /* .table-image {
  td ,th {
    vertical-align;
  }
} */
  /* The Modal (background) */
  .modal {
    display: none;
    /* Hidden by default */
    position: fixed;
    /* Stay in place */
    z-index: 1;
    /* Sit on top */
    padding-top: 100px;
    /* Location of the box */
    left: 0;
    top: 0;
    width: 100%;
    /* Full width */
    height: 100%;
    /* Full height */
    overflow: auto;
    /* Enable scroll if needed */
    background-color: rgb(0, 0, 0);
    /* Fallback color */
    background-color: rgba(0, 0, 0, 0.4);
    /* Black w/ opacity */
  }

  /* Modal Content */
  .modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 20px;
    border: 1px solid #888;
    width: 80%;
  }

  /* The Close Button */
  .close {
    color: #aaaaaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }

  .close:hover,
  .close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
  }

  .modal-backdrop {
    display: none;
    z-index: 1040 !important;
  }

  .modal-content {
    margin: 2px auto;
    z-index: 1100 !important;
  }

  .orgtxt {
    position: relative;
    top: 50px;
    text-align: center;
  }

  .btn-addEvent {
    text-align: center;
  }
</style>

<body>
  {% block content %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'account:organizer' %}"><b>MetroEvents</b></a>
        </li>
      </ul>
    </div>

    <span class="hello-msg">Hello, {{request.user}}</span>
    <span><a class="hello-msg" href="{% url 'account:logout' %}" style="color: white;">Logout</a></span>

  </nav>
  <div class="orgtxt">
    <h2>Organizer Dashboard</h2>
  </div>
  <!-- Table Events-->

  <div class="container-fluid">
    <div class="container">
      <h4>My Organized Events</h4>
      {% for message in messages %}
      <p style="text-align: center;" id="messages">{{message}}</p>
      {% endfor %}
      <div class="row">
        <div class="col-12">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th id="eventtbl-col1" style="text-align: center">Event ID</th>
                <th id="eventtbl-col2" style="text-align: center">Event Type</th>
                <th id="eventtbl-col3" style="text-align: center">Start Date</th>
                <th id="eventtbl-col4" style="text-align: center">End Date</th>
                <th id="eventtbl-col5" style="text-align: center">Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for myevent in myEvents %}
              <tr>
                <td style="text-align: center">{{myevent.id}}</td>
                <td style="text-align: center">{{myevent.event_type}}</td>
                <td style="text-align: center">{{myevent.start_date}}</td>
                <td style="text-align: center">{{myevent.end_date}}</td>
                <td style="text-align: center">
                  <button class="btn btn-primary" type="button" id="edit_eventbtn" data-toggle="modal"
                    data-target="#ModalEditEvent-{{myevent.id}}"><b>VIEW/EDIT EVENT</b></button>

                  <button class="btn btn-danger" type="button" id="cancel_eventbtn" data-toggle="modal"
                    data-target="#ModalDeleteEvent-{{myevent.id}}"><b>REMOVE
                      EVENT</b></button>


                  <!-- Edit Modal -->
                  <div class="modal fade" id="ModalEditEvent-{{myevent.id}}" tabindex="-1"
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="col-12 modal-title text-center"><b>View/Edit</b></h5>
                        </div>
                        <div id="UpdateEventForm">
                          <form method="post">
                            {% csrf_token %}
                            <div class="modal-body">
                              <!--Event Type-->
                              <div class="row text-center">
                                <div class="col-lg-12">
                                  <label><b>Event Type</b></label>
                                  <input type="text" class="form-control" id="id-event-title" name="event_type"
                                    placeholder="Event Type" required value="{{myevent.event_type}}" style="
                                    text-align: center;" />
                                </div>
                              </div>
                              <!--END Event Type-->
                              <br>
                              <!-- Start Date and End Date-->
                              <div class="row text-center justify-content-center">
                                <div class="col-lg-6">
                                  <label for="decription"><b>Start Date</b></label>
                                  <input id="start_date" type="date" name="start_date" value="{{myevent.start_date}} "
                                    style="
                                  text-align: center;" required>
                                </div>
                                <div class="col-lg-6">
                                  <label for="decription"><b>End Date</b></label>
                                  <input id="end_date" type="date" name="end_date" value="{{myevent.end_date}}" style="
                                  text-align: center;" required>
                                </div>
                              </div>
                              <br>
                              <div class="row text-center justify-content-center">
                                <div class="col-lg-6">
                                  <label for="decription"><b>No. of Participants</b></label>
                                  <input id="participants" class=" text-center" type="number" name="participants"
                                    value="{{myevent.participants.count}}" readonly>
                                </div>
                                <div class="col-lg-6">
                                  <label for="decription"><b>No. of Upvotes</b></label>
                                  <input id="date_started" type="number" name="upvotes" value="{{myevent.upvotes}}"
                                    readonly style="text-align: center;">
                                </div>
                              </div>
                              <br>
                              <input type="text" value="{{myevent.id}}" name="event_id" hidden readonly />
                              <div class="modal-footer justify-content-center">
                                <button type="submit" id="EditBtn" name="EditBtn" class="btn btn-primary">
                                  Update
                                </button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                                  Cancel
                                </button>
                              </div>
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                  <!-- Modal Delete -->
                  <div class="modal fade" id="ModalDeleteEvent-{{myevent.id}}" tabindex="-1"
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="col-12 modal-title text-center"><b>Remove/Delete</b></h5>
                        </div>

                        <form id="DeleteEventForm" method="post">
                          {% csrf_token %}
                          <div class="modal-body">
                            <input type="text" name="eventID" hidden />
                            Are you sure you want to delete this event?
                          </div>
                          <input type="text" value="{{myevent.id}}" name="event_id" hidden readonly />
                          <div class="modal-footer justify-content-center">
                            <button type="submit" name="DeleteBtn" class="btn btn-danger">
                              Yes
                            </button>
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                              No
                            </button>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                  <!-- Modal Delete Ends -->
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <div class="btn-addEvent">
            <a type="button" class="button btn btn-primary" href="{% url 'account:addEvent' %}">
              <b>ADD EVENTS</b></a>
          </div>

        </div>
      </div>
    </div>

    <!-- Table Requests to Join-->
    <div class="container">
      <h4>Join Requests</h4>
      <div class="row">
        <div class="col-12">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th id="reqeventtbl-col1" style="text-align: center">User ID</th>
                <th id="reqeventtbl-col2" style="text-align: center">Username</th>
                <th id="reqeventtbl-col3" style="text-align: center">Event ID</th>
                <th id="reqeventtbl-col4" style="text-align: center">Event Type</th>
                <th id="reqeventtbl-col5" style="text-align: center">Manage</th>
              </tr>
            </thead>
            <tbody id="JoinRequest-table">
              {% for req in requests %}
              <tr>
                <td style="text-align: center">{{req.user_id}}</td>
                <td style="text-align: center">{{req.user}}</td>
                <td style="text-align: center">{{req.event_id}}</td>
                <td style="text-align: center">{{req.event}}</td>
                <td style="text-align: center">
                  <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="number" name="request_id" value="{{req.id}}" hidden readonly />
                    <input type="number" name="event_id" value="{{req.event_id}}" hidden readonly />
                    <input type="number" name="user_id" value="{{req.user_id}}" hidden readonly />
                    <button class="btn btn-primary" type="submit" name="acceptRequestbtn"><b>ACCEPT</b></button>
                    <button class="btn btn-danger" type="submit" name="denyRequestbtn"><b>DECLINE</b></button>
                  </form>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


  </div>
  {% endblock content %}
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>